### ISSUE TITLE
Silent Reject and combine with other spam filters

### ISSUE THREAD

**Issue by social-butterfly** [xini/silverstripe-spamprotection-honeypot#1]
Is there a way to silently reject a spam message - better not to give the spammer any indication that it was rejected. Also can this honeypot method be combined with another spam protector extension (e.g. Math protector)? In the .yml it's defined as 'default_spam_protector'

**Comment by xini** [comment]
I'm not sure silently rejecting submissions is a good idea. Actual users might expect a reply when instead their message was dropped. 

You can fork this module and add additional fields to it, yes. And with that you could add a math protector functionality. I based this module off two others and added additional fields as well to basically have three different honey pots.

I think the `default_spam_protector` setting really is what it says on the label: a default for all forms. If you want a different one for a certain form, you can override the default:
```
$form->enableSpamProtection([
    'protector' => MathSpamProtector::class
]);
```

**Comment by social-butterfly** [comment]
I thought silent rejection could be an option, doesn't need to be default behaviour. However, I don't see how a normal user fills in a hidden form field (unless they exactly know what they're doing) nor sending a contact form in let's say 5-8 seconds (if you choose the timer) - even when using a form fill plugin. So my guess is that almost exclusively bots/scripts will trigger a rejection.

Regarding the default_spam_protector, it's probably more a question for the spam protection module but I was wondering if you can combine multiple individual extensions by putting them in the yaml. E.g. your honeypot extension and and existing math extension... but I never saw in any documentation anything else than ''default_spam_protector'. Probably have to build my own extension then... Cheers

**Comment by xini** [comment]
No worries. Yes, I guess you'll have to extend the spam protection module to allow for this.
